/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author danie
 */
public class Puntajes extends javax.swing.JFrame {

    /**
     * Creates new form puntajes
     */
    public Puntajes() 
    {
         initComponents();
        this.setLocationRelativeTo(null);
        
                
        Conexion con = new Conexion();
        con.ConsultarTop10(tablePuntuacion);
     
        this.tablePuntuacion.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 14));
        this.tablePuntuacion.getTableHeader().setOpaque(false);
        this.tablePuntuacion.getTableHeader().setBackground(new Color(5, 129, 179));
        this.tablePuntuacion.getTableHeader().setForeground(new Color(255,255,255));
        
        if(this.pnlJugadorActual.isVisible())
        {
            Jugador jugador = new Jugador();
            this.txtPosicion.setText(String.valueOf(jugador.getPosicion()));
            this.txtNombre.setText(jugador.getUsername());
            this.txtPuntuacion.setText(String.valueOf(jugador.getPuntuacion()));
        }
    }
    
    public void setPnlJugadorActual(boolean condicion) 
    {
        this.pnlJugadorActual.setVisible(condicion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePuntuacion = new javax.swing.JTable();
        pnlJugadorActual = new javax.swing.JPanel();
        lblJugadorActual = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        txtPosicion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtPuntuacion = new javax.swing.JLabel();
        lblPuntuacion1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Top 10 Jugadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        tablePuntuacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Nombre", "Puntuación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePuntuacion.setFocusable(false);
        tablePuntuacion.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablePuntuacion.setOpaque(false);
        tablePuntuacion.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tablePuntuacion.setShowVerticalLines(false);
        tablePuntuacion.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablePuntuacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 480, 190));

        pnlJugadorActual.setName(""); // NOI18N
        pnlJugadorActual.setOpaque(false);
        pnlJugadorActual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugadorActual.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblJugadorActual.setForeground(new java.awt.Color(0, 0, 102));
        lblJugadorActual.setText("Jugador Actual");
        pnlJugadorActual.add(lblJugadorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        lblPosicion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPosicion.setForeground(new java.awt.Color(0, 0, 102));
        lblPosicion.setText("Posición: ");
        pnlJugadorActual.add(lblPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtPosicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPosicion.setForeground(new java.awt.Color(0, 0, 102));
        txtPosicion.setText("21");
        pnlJugadorActual.add(txtPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 102));
        lblNombre.setText("Nombre: ");
        pnlJugadorActual.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 102));
        txtNombre.setText("HéctorLópez");
        pnlJugadorActual.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        txtPuntuacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPuntuacion.setForeground(new java.awt.Color(0, 0, 102));
        txtPuntuacion.setText("500");
        pnlJugadorActual.add(txtPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lblPuntuacion1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPuntuacion1.setForeground(new java.awt.Color(0, 0, 102));
        lblPuntuacion1.setText("Puntuación:");
        pnlJugadorActual.add(lblPuntuacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 20));

        getContentPane().add(pnlJugadorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 620, 180));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/imagenes/Background_TablaPuntajes.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJugadorActual;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblPuntuacion1;
    private javax.swing.JPanel pnlJugadorActual;
    private javax.swing.JTable tablePuntuacion;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPosicion;
    private javax.swing.JLabel txtPuntuacion;
    // End of variables declaration//GEN-END:variables
}
